### ISSUE TITLE
Ubuntu 20 Support

### ISSUE THREAD

**Issue by Song-Jingyu** [ganlumomo/BKISemanticMapping#3]
Hi Lu,

Hope you are doing well recently! Some students from the Mobile Robotics course did try to build this repo on Ubuntu 20 which is not initially supported. Is it possible to create a new branch adding these modifications? I also noticed the student already created a pull request. So you can directly see the changes.

**Comment by ganlumomo** [comment]
Hi Jingyu,

I have processed the pull request. Let me know if that works.
